# The NumPy ndarray: A Multidimensional Array Object
- The NumPy ndarray
    - data.shape
    - data.dtype
- Creating ndarrays
    - np.array
    - np.zeros
    - np.ones
    - np.empty
    - np.arange
- Data Types for ndarrays
    - data.astype
- Operations between Arrays and Scalars
    - vectorization
    - broadcasting

## The NumPy ndarray
- `shape`, a tuple indicating the size of each dimension
- `dtype`, an object describing the data type of the array

In [1]:
import numpy as np

data = np.random.randn(2, 3)
data

array([[-0.77811319, -0.61365309, -1.41085337],
       [ 0.34646161,  0.24173114, -1.36464591]])

In [2]:
data * 10

array([[ -7.78113187,  -6.13653093, -14.10853372],
       [  3.4646161 ,   2.41731135, -13.6464591 ]])

In [3]:
data + data

array([[-1.55622637, -1.22730619, -2.82170674],
       [ 0.69292322,  0.48346227, -2.72929182]])

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')

## Creating ndarrays
- `np.array` tries to infer a good data type for the array that it creates
- The data type is stored in a special `dtype` metadata object

In [6]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [7]:
arr1.dtype

dtype('float64')

In [8]:
data2 = [6, 7, 8, 0, 1]
arr2 = np.array(data2)
arr2

array([6, 7, 8, 0, 1])

In [9]:
arr2.dtype

dtype('int64')

- `zeros` and `ones` create arrays of 0’s or 1’s, respectively, with a given length or shape
- `empty` creates an array without initializing its values to any particular value
- To create a higher dimensional array with these methods, pass a tuple for the shape

In [10]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [11]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [12]:
np.empty((2, 3, 2))

array([[[  0.00000000e+000,   0.00000000e+000],
        [  2.15835751e-314,   2.15837254e-314],
        [  2.21734990e-314,   2.21735767e-314]],

       [[  2.15841307e-314,   0.00000000e+000],
        [  2.15437345e-314,   2.15841316e-314],
        [  0.00000000e+000,   8.34402830e-309]]])

In [13]:
np.ones((2, 3, 2))

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]])

- `arange` is an array-valued version of the built-in Python range function

In [14]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Table 4-1. Array creation functions

| Function	| Description |
| --- | --- |
| array	| Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a dtype or explicitly specifying a dtype. Copies the input data by default.|
| asarray	| Convert input to ndarray, but do not copy if the input is already an ndarray|
| arange	| Like the built-in range but returns an ndarray instead of a list.|
| ones, ones_like	| Produce an array of all 1’s with the given shape and dtype. ones_like takes another array and produces a ones array of the same shape and dtype.|
| zeros, zeros_like	| Like ones and ones_like but producing arrays of 0’s instead|
| empty, empty_like	| Create new arrays by allocating new memory, but do not populate with any values like ones and zeros|
| full, full_like	| Produce an array of the given shape and dtype with all values set to the indicated “fill value”. full_like takes another array and produces a a filled array of the same shape and dtype.|
| eye, identity	| Create a square N x N identity matrix (1’s on the diagonal and 0’s elsewhere)|

## Data Types for ndarrays

In [15]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [16]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2.dtype

dtype('int32')

Table 4-2. NumPy data types

| Type	| Type Code	| Description |
| --- | --- | --- |
| int8, uint8	| i1, u1	| Signed and unsigned 8-bit (1 byte) integer types|
| int16, uint16	| i2, u2	| Signed and unsigned 16-bit integer types|
| int32, uint32	| i4, u4	| Signed and unsigned 32-bit integer types|
| int64, uint64	| i8, u8	| Signed and unsigned 32-bit integer types|
| float16	| f2	| Half-precision floating point|
| float32	| f4 or f	| Standard single-precision floating point. Compatible with C float|
| float64	| f8 or d	| Standard double-precision floating point. Compatible with C double and Python float object|
| float128	| f16 or g	| Extended-precision floating point|
| complex64, complex128, complex256	| c8, c16, c32	| Complex numbers represented by two 32, 64, or 128 floats, respectively|
| bool	| ?	| Boolean type storing True and False values|
| object	| O	| Python object type, a value can be any Python object|
| string_	| S	| Fixed-length ASCII string type (1 byte per character). For example, to create a string dtype with length 10, use 'S10'.|
| unicode_	| U	| Fixed-length unicode type (number of bytes platform specific). Same specification semantics as string_ (e.g. 'U10').|

You can explicitly convert or cast an array from one dtype to another using ndarray’s `astype` method:

In [17]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [18]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

If I cast some floating point numbers to be of integer dtype, the decimal part will be truncated:

In [19]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [20]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

you can use astype to convert strings representing numbers to numeric form:

In [21]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

You can also use another array’s dtype attribute:

In [22]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
calibers

array([ 0.22 ,  0.27 ,  0.357,  0.38 ,  0.44 ,  0.5  ])

In [24]:
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

Calling `astype` always creates a new array (a copy of the data), even if the new dtype is the same as the old dtype.

There are shorthand type code strings you can also use to refer to a dtype:

In [25]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([6, 0, 7, 0, 8, 0, 1, 0], dtype=uint32)

## Operations between Arrays and Scalars
Arrays are important because they enable you to express batch operations on data without writing any for loops. NumPy users call this `vectorization`.

In [26]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [27]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [28]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

Arithmetic operations with scalars are as you would expect, propagating the value to each element:

In [29]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [30]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

Operations between differently sized arrays is called `broadcasting`.