# The NumPy Transposing and Swapping Axes
- data.T
- np.dot
- data.swapaxes

`Transposing` is a special form of reshaping which similarly returns a view on the underlying data without copying anything.  Arrays have the `transpose` method and also the special T attribute:

In [2]:
import numpy as np

arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

When doing matrix computations, you will do this very often, like for example computing the inner matrix product $X^TX$ using `np.dot`:

In [4]:
arr = np.random.randn(6, 3)
arr

array([[ 0.64054029,  0.17807626, -1.40214664],
       [ 0.90348214, -1.69796605,  1.43242689],
       [-0.40682134, -1.37678192,  1.13991128],
       [-0.12307173, -1.85460062, -0.40159431],
       [-0.33847489,  0.76092381,  2.65556841],
       [-0.6007457 ,  0.95456543, -0.2499418 ]])

In [5]:
np.dot(arr.T, arr)

array([[  1.88268273,  -1.46266847,  -0.7669664 ],
       [ -1.46266847,   9.74007195,  -1.72441403],
       [ -0.7669664 ,  -1.72441403,  12.59305221]])

For higher dimensional arrays, transpose will accept a tuple of axis numbers to permute the axes (for extra mind bending):

In [6]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [7]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

Simple transposing with .T is a special case of swapping axes. ndarray has the method `swapaxes` which takes a pair of axis numbers:

In [8]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [9]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])