# NumPy Linear Algebra
- x.dot(y)
- inv
- qr

As such, there is a function `dot`, both an array method, and a function in the numpy namespace, for matrix multiplication:

In [1]:
import numpy as np

x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [2]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [3]:
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

A matrix product between a 2D array and a suitably sized 1D array results in a 1D array:

In [4]:
np.dot(x, np.ones(3))

array([  6.,  15.])

`numpy.linalg` has a standard set of matrix decompositions and things like inverse and determinant.

In [6]:
from numpy.linalg import inv, qr

X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)

array([[ 0.27535679, -0.29940661, -0.24919197, -0.11354619,  0.22586209],
       [-0.29940661,  3.39855131, -0.94628098,  2.89420707, -2.75269607],
       [-0.24919197, -0.94628098,  1.0952727 , -1.30625692,  0.95091947],
       [-0.11354619,  2.89420707, -1.30625692,  3.02632236, -2.67395787],
       [ 0.22586209, -2.75269607,  0.95091947, -2.67395787,  2.56108371]])

In [7]:
mat.dot(inv(mat))

array([[  1.00000000e+00,  -8.45972065e-17,   2.40859319e-16,
         -4.38243737e-16,   1.47411539e-16],
       [  1.20830595e-16,   1.00000000e+00,   5.92450032e-17,
         -6.51858213e-16,   5.00487197e-16],
       [ -2.60537710e-16,  -4.95372794e-16,   1.00000000e+00,
          5.01736445e-16,  -2.03563464e-15],
       [ -1.12993151e-16,  -2.04126010e-15,  -4.09497337e-17,
          1.00000000e+00,  -1.87859419e-15],
       [ -5.15614758e-16,   5.38809025e-15,   1.29434018e-16,
          2.83813343e-15,   1.00000000e+00]])

In [9]:
q, r = qr(mat)
r

array([[-11.14125498,   0.20477295,  -7.69485473,  -4.81600683,  -0.9433097 ],
       [  0.        ,  -3.25643221,   1.4858105 ,   1.63646804,
         -2.53372026],
       [  0.        ,   0.        ,  -5.77089451, -13.16018677,
        -11.83448889],
       [  0.        ,   0.        ,   0.        ,  -2.79781132,
         -3.04100929],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.21203866]])

Table 4-7. Commonly-used numpy.linalg functions

Function | Description
---------|------------
diag | Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array, or convert a 1D array into a square matrix with zeros on the off-diagonal
dot | Matrix multiplication
trace | Compute the sum of the diagonal elements
det | Compute the matrix determinant
eig | Compute the eigenvalues and eigenvectors of a square matrix
inv | Compute the inverse of a square matrix
pinv | Compute the Moore-Penrose pseudo-inverse inverse of a matrix
qr | Compute the QR decomposition
svd | Compute the singular value decomposition (SVD)
solve | Solve the linear system Ax = b for x, where A is a square matrix
lstsq | Compute the least-squares solution to Ax = b