# Universal Functions: Fast Element-wise Array Functions
- np.sqrt(data)
- np.exp(data)

A universal function, or `ufunc`, is a function that performs elementwise operations on data in ndarrays. 

Many ufuncs are simple elementwise transformations, like sqrt or exp:

In [2]:
import numpy as np

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

These are referred to as `unary ufuncs`. Others, such as add or maximum, take 2 arrays (thus, `binary ufuncs`) and return a single array as the result:

In [5]:
x = np.random.randn(8)
x

array([ 0.85932781, -0.04627684,  0.76666254, -0.63072546,  0.35873609,
       -0.14751691,  0.58350359, -0.7317197 ])

In [6]:
y = np.random.randn(8)
y

array([ 0.25023887,  2.01529489,  1.2875973 ,  0.72838554, -1.37287257,
        0.22068954, -0.71569382,  1.09786465])

In [7]:
np.maximum(x, y) # element-wise maximum

array([ 0.85932781,  2.01529489,  1.2875973 ,  0.72838554,  0.35873609,
        0.22068954,  0.58350359,  1.09786465])

While not common, a ufunc can return multiple arrays. modf is one example, a vectorized version of the built-in Python divmod: it returns the fractional and integral parts of a floating point array:

In [8]:
arr = np.random.randn(7) * 5
arr

array([-6.58856799,  0.12325146, -3.10962427, -0.83290625,  4.46950588,
       -5.37143038, -2.6136427 ])

In [9]:
np.modf(arr)

(array([-0.58856799,  0.12325146, -0.10962427, -0.83290625,  0.46950588,
        -0.37143038, -0.6136427 ]), array([-6.,  0., -3., -0.,  4., -5., -2.]))

Table 4-3. Unary ufuncs

Function | Description
---------|------------
abs, fabs | Compute the absolute value element-wise for integer, floating point, or complex values. Use fabs as a faster alternative for non-complex-valued data
sqrt | Compute the square root of each element. Equivalent to arr ** 0.5
square | Compute the square of each element. Equivalent to arr ** 2
exp | Compute the exponent ex of each element
log, log10, log2, log1p | Natural logarithm (base e), log base 10, log base 2, and log(1 + x), respectively
sign | Compute the sign of each element: 1 (positive), 0 (zero), or -1 (negative)
ceil | Compute the ceiling of each element, i.e. the smallest integer greater than or equal to each element
floor | Compute the floor of each element, i.e. the largest integer less than or equal to each element
rint | Round elements to the nearest integer, preserving the dtype
modf | Return fractional and integral parts of array as separate array
isnan | Return boolean array indicating whether each value is NaN (Not a Number)
isfinite, isinf | Return boolean array indicating whether each element is finite (non-inf, non-NaN) or infinite, respectively
cos, cosh, sin, sinh, tan, tanh | Regular and hyperbolic trigonometric functions
arccos, arccosh, arcsin, arcsinh, arctan, arctanh | Inverse trigonometric functions
logical_not | Compute truth value of not x element-wise. Equivalent to -arr.

Table 4-4. Binary universal functions

Function | Description
---------|------------
add | Add corresponding elements in arrays
subtract | Subtract elements in second array from first array
multiply | Multiply array elements
divide, floor_divide | Divide or floor divide (truncating the remainder)
power | Raise elements in first array to powers indicated in second array
maximum, fmax | Element-wise maximum. fmax ignores NaN
minimum, fmin | Element-wise minimum. fmin ignores NaN
mod | Element-wise modulus (remainder of division)
copysign | Copy sign of values in second argument to values in first argument
greater, greater_equal, less, less_equal, equal, not_equal | Perform element-wise comparison, yielding boolean array. Equivalent to infix operators >, >=, <, <=, ==, !=
logical_and, logical_or, logical_xor | Compute element-wise truth value of logical operation. Equivalent to infix operators & \|, ^