# The NumPy Indexing and Slicing
- Basic Indexing and Slicing
    - Indexing with slices
- Boolean Indexing
- Fancy Indexing
    - np.ix_

## Basic Indexing and Slicing

In [2]:
import numpy as np

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5]

5

In [4]:
arr[5:8]

array([5, 6, 7])

In [5]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

Array slices are `views` on the original array. This means that **the data is not copied, and any modifications to the view will be reflected in the source array**:

In [6]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [7]:
arr_slice[1] = 12345
arr_slice

array([   12, 12345,    12])

In [8]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [9]:
arr_slice[:] = 64
arr_slice

array([64, 64, 64])

In [10]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In a two-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays:

In [11]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

These are equivalent:

In [12]:
arr2d[0][2]

3

In [13]:
arr2d[0, 2]

3

![1](https://www.safaribooksonline.com/library/view/python-for-data/9781491957653/assets/pyda_0401.png)

Figure 4-1. Indexing elements in a NumPy array

In the 2 × 2 × 3 array arr3d:

In [14]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

arr3d[0] is a 2 × 3 array:

In [15]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

Both scalar values and arrays can be assigned to arr3d[0]:

In [17]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Similarly, arr3d[1, 0] gives you all of the values whose indices start with (1, 0), forming a 1-dimensional array:

In [19]:
arr3d[1, 0]

array([7, 8, 9])

### INDEXING WITH SLICES

In [20]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [23]:
arr2d[1, :2]

array([4, 5])

In [24]:
arr2d[2, :1]

array([7])

In [25]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [27]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

![4-2](https://www.safaribooksonline.com/library/view/python-for-data/9781491957653/assets/pyda_0402.png)

Figure 4-2. Two-dimensional array slicing

## Boolean Indexing

In [28]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='|S4')

In [29]:
data = np.random.randn(7, 4)
data

array([[ 0.92421297,  1.635549  , -0.75400028, -0.56840518],
       [ 0.4868799 ,  2.79703765,  0.52686199,  1.52560872],
       [-0.03136536, -1.23643309, -0.59230943,  0.23394715],
       [ 0.03744625,  1.04670542,  0.38556559, -0.98470501],
       [ 0.88631849,  1.5252055 ,  1.39992577,  0.2028578 ],
       [-0.52393985,  0.02174075,  0.26490291, -0.038142  ],
       [ 1.3779059 ,  0.89653446, -1.37308354,  0.69683512]])

In [30]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [31]:
data[names == 'Bob']

array([[ 0.92421297,  1.635549  , -0.75400028, -0.56840518],
       [ 0.03744625,  1.04670542,  0.38556559, -0.98470501]])

In [32]:
data[names == 'Bob', 2:]

array([[-0.75400028, -0.56840518],
       [ 0.38556559, -0.98470501]])

In [33]:
data[names == 'Bob', 3]

array([-0.56840518, -0.98470501])

In [34]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [35]:
data[~(names == 'Bob')]

array([[ 0.4868799 ,  2.79703765,  0.52686199,  1.52560872],
       [-0.03136536, -1.23643309, -0.59230943,  0.23394715],
       [ 0.88631849,  1.5252055 ,  1.39992577,  0.2028578 ],
       [-0.52393985,  0.02174075,  0.26490291, -0.038142  ],
       [ 1.3779059 ,  0.89653446, -1.37308354,  0.69683512]])

In [36]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [37]:
data[mask]

array([[ 0.92421297,  1.635549  , -0.75400028, -0.56840518],
       [-0.03136536, -1.23643309, -0.59230943,  0.23394715],
       [ 0.03744625,  1.04670542,  0.38556559, -0.98470501],
       [ 0.88631849,  1.5252055 ,  1.39992577,  0.2028578 ]])

To set all of the negative values in data to 0 we need only do:

In [38]:
data[data < 0] = 0
data

array([[ 0.92421297,  1.635549  ,  0.        ,  0.        ],
       [ 0.4868799 ,  2.79703765,  0.52686199,  1.52560872],
       [ 0.        ,  0.        ,  0.        ,  0.23394715],
       [ 0.03744625,  1.04670542,  0.38556559,  0.        ],
       [ 0.88631849,  1.5252055 ,  1.39992577,  0.2028578 ],
       [ 0.        ,  0.02174075,  0.26490291,  0.        ],
       [ 1.3779059 ,  0.89653446,  0.        ,  0.69683512]])

Setting whole rows or columns using a 1D boolean array is also easy:

In [39]:
data[names != 'Joe'] = 7
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.4868799 ,  2.79703765,  0.52686199,  1.52560872],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  0.02174075,  0.26490291,  0.        ],
       [ 1.3779059 ,  0.89653446,  0.        ,  0.69683512]])

## Fancy Indexing
`Fancy indexing` is a term adopted by NumPy to describe indexing using integer arrays. Suppose we had a 8 × 4 array:

In [40]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

To select out a subset of the rows in a particular order, you can simply pass a list or ndarray of integers specifying the desired order:

In [41]:
arr[[4, 3, 0, 6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [42]:
arr[[-3, -5, -7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

Passing multiple index arrays does something slightly different; it selects a 1D array of elements corresponding to each tuple of indices:

In [43]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [44]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [45]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

Another way is to use the np.ix_ function, which converts two 1D integer arrays to an indexer that selects the square region:

In [46]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])